import requests
from config import OLLAMA_MODEL


OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = OLLAMA_MODEL

def generate_queries(
    query: str,
    num_queries: int = 3,
) -> list[str]:

    prompt = f"""
You are a search query expansion system for a technical documentation RAG system.

Generate {num_queries} alternative search queries for the user's information need.

Rules:
- Preserve the original intent exactly.
- Each query must search for the same information.
- Use different wording or perspectives.
- Preserve important technical terms.
- Do not answer the question.
- Do not introduce unrelated technologies or assumptions.
- Keep queries concise.
- Return exactly one query per line.
- Do not number the queries.
- Do not use markdown.
- Do not explain anything.

User query:
{query}
"""

    response = requests.post(
        OLLAMA_URL,
        json={
            "model": MODEL_NAME,
            "prompt": prompt,
            "stream": False,
        },
        timeout=60,
    )

    response.raise_for_status()

    output = response.json()["response"].strip()

    queries = []

    for line in output.splitlines():

        line = line.strip()

        if not line:
            continue

        # Remove common numbering generated by the LLM.
        if line[0:2].strip(". ").isdigit():
            line = line[2:].strip()

        if line.startswith(("-", "*")):
            line = line[1:].strip()

        line = line.strip("\"'")

        if line:
            queries.append(line)

    return queries[:num_queries]